Soal 1. Buatlah sebuah array dengan perintah arrange yang nilai start dan end adalah sebuah input! Dari array yang terbentuk tersebut, buatlah versi 2 dan 3 dimensinya!

In [6]:
import pandas as pd
import numpy as np

Mulai = int(input("Mulai :"))
Selesai = int(input("Selesai :"))

a = np.arange(Mulai, Selesai)
a

Mulai :1
Selesai :28


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [19]:
dua_dimensi = a.reshape(3, 9)
dua_dimensi

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [20]:
tiga_dimensi = a.reshape(3,3,3)
tiga_dimensi

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

Soal 2. Buatlah sebuah array 1 dimensi dari data random integer sebanyak “n”, dimana “n” tersebut adalah sebuah input ! Batasan random juga ditentukan dalam input. Ubahlah array 1 dimensi tersebut ke dalam bentuk 2 dimensi atau matrix! Setelah diubah ke bentuk 2 dimensi, setiap barisnya baliklah urutan datanya! Misalnya dari 1, 2, 3 menjadi 3, 2, 1.

In [21]:
n = int(input("Banyak Data :"))
Mulai = int(input("Mulai :"))
Selesai = int(input("Selesai :"))



Banyak Data :16
Mulai :1
Selesai :50


In [24]:
data = np.random.randint(Mulai, Selesai, n)
data

array([22, 25, 27, 40,  2, 36, 14, 13, 38, 35, 17, 33, 30, 47, 42, 15])

In [25]:
# dua dimensi
Dua_Dimensi = data.reshape(4,4)
Dua_Dimensi

array([[22, 25, 27, 40],
       [ 2, 36, 14, 13],
       [38, 35, 17, 33],
       [30, 47, 42, 15]])

In [26]:
# Tukar Posisi

Dua_Dimensi[:, ::-1]

array([[40, 27, 25, 22],
       [13, 14, 36,  2],
       [33, 17, 35, 38],
       [15, 42, 47, 30]])

Soal 3. Buatlah sebuah array 2 dimensi dengan ukuran 10 x 10! Isi dari array tersebut adalah: • Sisi luarnya merupakan angka 4. • Selain sisi luar, angka yang ditampilkan adalah 0.

In [30]:
x = np.ones((10,10)) * 4
x

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [31]:
x[1:-1, 1:-1] = 0
x

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [34]:
x[1:9, 1:9] = 0
x

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])