In [1]:
!pip install numpy

In [5]:
import numpy as np

a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a[0])

[1 2 3 4]


In [6]:
import numpy as np

a = np.array([1, 2, 3])

In [7]:
a

array([1, 2, 3])

In [8]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [10]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
print(np.arange(4))
print(np.arange(0,10,3)) # (start, stop, step)

[0 1 2 3]
[0 3 6 9]


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.append(arr, [1,2])


array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [14]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [15]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [17]:
array_example.ndim

3

In [19]:
array_example.size

24

In [20]:
array_example.shape

(3, 2, 4)

In [21]:
arr_one = np.array([[1, 2, 3, 4, 5]])

arr_one.ndim

2

In [22]:
arr_one.size

5

In [23]:
arr_one.shape

(1, 5)

In [25]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [26]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [30]:
a.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [31]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [32]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [33]:
# You can use np.newaxis to add a new axis:

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [34]:
# You can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [35]:
# for a column vector, You can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [36]:
# You can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [37]:
# You can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [38]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [39]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
# You can easily print all of the values in the array that are less than 5

print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [41]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [42]:
# You can select elements that are divisible by 2

divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [43]:
# you can select elements that satisfy two conditions using the & and | operators

c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


In [46]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [50]:
a_1 = np.array([[1, 1],
                [2, 2]])

In [51]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [52]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [53]:
# Or stack them horizontally with hstack

np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [55]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [56]:
# If you wanted to split this array into three equally shaped arrays

np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [57]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
# You can create a new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
# Using the copy method will make a complete copy of the array and its data (a deep copy).

c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
a = np.array([1, 2, 3, 4])

# Add all of the elements in the array
a.sum()

10

In [61]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [63]:
# You can sum the rows

b.sum(axis=0)

array([3, 3])

In [64]:
# You can sum the columns

b.sum(axis=1)

array([2, 4])

In [65]:
data = np.array([1, 2])
data

array([1, 2])

In [66]:
ones = np.ones(2)
ones

array([1., 1.])

In [67]:
data + ones

array([2., 3.])

In [68]:
data * data

array([1, 4])

In [69]:
data / data

array([1., 1.])

In [70]:
data * 2

array([2, 4])

In [71]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [72]:
A.sum()

4.8595784

In [73]:
A.min()

0.05093587

In [74]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [75]:
A.max()

0.82485143

In [76]:
A.max(axis=1)  

# axis = 0 --- baris
# axis = 1 --- kolom

array([0.5510652 , 0.55645993, 0.82485143])

In [77]:
A.max(axis=0)  

array([0.54627315, 0.82485143, 0.40067661, 0.56917101])

In [78]:
A.std()   #standar deviation

0.21392120766089617

In [79]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.54497743, 0.75795271],
       [0.94431549, 0.81807598],
       [0.55080518, 0.01571563]])

In [80]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.87005292 0.88131569]
 [0.06593642 0.40634662]
 [0.53511389 0.36987493]]


In [81]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [82]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [83]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [84]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [85]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


In [86]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [87]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [88]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


In [89]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [90]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [91]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


In [93]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [94]:
print(data.T)   #transpose

[[1 3 5]
 [2 4 6]]


In [95]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [96]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [98]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


In [99]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [100]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [101]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [102]:
print(np.random.random((4,3,2)))

[[[0.42825535 0.23833018]
  [0.21181203 0.32370261]
  [0.75070658 0.40407346]]

 [[0.27025453 0.75595847]
  [0.69790836 0.07675868]
  [0.84338943 0.28509283]]

 [[0.45820634 0.31623973]
  [0.61345107 0.74824945]
  [0.25022791 0.11733202]]

 [[0.55622066 0.54966193]
  [0.09994894 0.38800474]
  [0.74765797 0.80983929]]]


In [103]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [104]:

# You can use flatten to flatten your array into a 1D array.

arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])